export declare const KERNEL_TERMINAL_LOGS: string[];
export declare function createLaptopTerminalCanvas(): HTMLCanvasElement;
export declare function updateLaptopTerminalCanvas(canvas: HTMLCanvasElement, logOffset?: number, cursorBlink?: boolean): void;
export declare function createDefconPosterCanvas(): HTMLCanvasElement;
export declare function createHackerThoughtsCanvas(): HTMLCanvasElement;
export declare function createAnonymousMaskCanvas(): HTMLCanvasElement;
export declare function createShelfHackerMatrixCanvas(): HTMLCanvasElement;
export declare function createAcousticFoamCanvas(): HTMLCanvasElement;
export declare function updateLeftHackerMonitorCanvas(canvas: HTMLCanvasElement, frame?: number): void;
export declare function updateRightHackerMonitorCanvas(canvas: HTMLCanvasElement, frame?: number): void;
export declare function createLeftDesktopHackerWallpaperCanvas(): HTMLCanvasElement;
export declare function createRightDesktopHackerWallpaperCanvas(): HTMLCanvasElement;
